version: '3.8'
services:
  backend:
    build: ./backend
    container_name: menugen-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data/images:/app/data/images
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: menugen-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
